### 리뷰 생성
POST http://localhost:10368/api/reviews
Accept: application/json
Content-Type: application/json
X-User-Id: 22

{
  "bookId": 1,
  "content": "hello",
  "rating": 3
}

### 책 전체 리뷰 조회
GET http://localhost:10368/api/reviews/books/1
Accept: application/json
Content-Type: application/json
X-User-Id: 22

### 리뷰 업데이트
PUT http://localhost:10368/api/reviews/8
Accept: application/json
Content-Type: application/json
X-User-Id: 22

{
  "content": "what's up",
  "rating": 3
}

###