server:
  port: 10368

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team4_dev?useSSL=false&serverTimezone=UTC
    username: project_be10_team4
    password: uEUklnkbk*7*_O4H
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10372/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,shutdown

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG