server:
  port: 10368
  max-http-request-header-size: 32KB

spring:
  application:
    name: review-api
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team4_dev?useSSL=false&serverTimezone=UTC
    username: project_be10_team4
    password: uEUklnkbk*7*_O4H
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://10.116.64.11:10372/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

minio:
  url: http://storage.java21.net:8000/
  accessKey: 49CWHX5eDpHYcKGTKltz
  secretKey: s1PNRymGqELYt7tThtqNvVbQaXwwP2ilLecLG7w2
  bucket: sajotuna-review

management:
  endpoints:
    web:
      exposure:
        include: health,info,shutdown
#
#logging:
#  level:
#    com.netflix.discovery: off
#    com.netflix.eureka: off
#    org.springframework.cloud.netflix.eureka: off